script to reload Gunicorn in a graceful way

diff --git a/0x1A-application_server/4-reload_gunicorn_no_downtime b/0x1A-application_server/4-reload_gunicorn_no_downtime
--- a/0x1A-application_server/4-reload_gunicorn_no_downtime
+++ b/0x1A-application_server/4-reload_gunicorn_no_downtime
@@ -1,3 +1,8 @@
 #!/usr/bin/env bash
 # Gracefully restart & update gunicorn workers
-pgrep gunicorn | xargs kill -HUP
+if pkill -HUP gunicorn; then
+        echo "Gunicorn workers were gracefully reloaded."
+else
+        echo "Error: Unable to reload Gunicorn workers." >&2
+        exit 1
+fi
